# Config format schema number
format_version: 4

###################
## Model options
model_params:
  model_architecture: "cylinder_asym"

  output_shape:
    - 480
    - 360
    - 32

  fea_dim: 9
  out_fea_dim: 256
  num_class: 21
  num_input_features: 16
  use_norm: True
  init_size: 32


###################
## Dataset options
dataset_params:
  dataset_type: "cylinder_dataset"
  pc_dataset_type: "SemKITTI_custom"
  ignore_label: 0
  return_test: False
  fixed_volume_space: True
  label_mapping: "./config/label_mapping/semantic-kitti-weather-mini.yaml"
  max_volume_space:
    - 50
    - 3.1415926
    - 2
  min_volume_space:
    - 0
    - -3.1415926
    - -4


###################
## Data_loader options
train_data_loader:
  data_path: "/home/ailab/AILabDataset/01_Open_Dataset/02_SemanticKITTI/SemanticKITTI_w_images/sequences"
  imageset: "train"
  return_ref: True
  batch_size: 2
  shuffle: True
  num_workers: 4

val_data_loader:
  data_path: "/home/ailab//AILabDataset/02_Custom_Dataset/16_SemanticKITTI_adverse_weather/ours_new/rain_20/sequences, /home/ailab//AILabDataset/02_Custom_Dataset/16_SemanticKITTI_adverse_weather/ours_new/rain_10/sequences, /home/ailab/AILabDataset/01_Open_Dataset/02_SemanticKITTI/SemanticKITTI_w_images/sequences"
  imageset: "val"
  return_ref: True
  batch_size: 1
  shuffle: False
  num_workers: 4


###################
## Train params
train_params:
  model_load_path: "./logs/ours_train_normal_mixed_rain/model_load.pt"
  model_save_path: "./logs/ours_train_normal_mixed_rain/model_save.pt"
  log_save_path: "./logs/ours_train_normal_mixed_rain"
  checkpoint_every_n_steps: 4599
  max_num_epochs: 20
  eval_every_n_steps: 4599
  learning_rate: 0.001
